#!/usr/bin/perl

# dt
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Thu Sep 16 11:51:13 2004

package MY_PACKAGE;
use strict;

my $tlast;
my $tmin;
my $tmax;
my $cnt = 0;
while(<>) {
    if(/time stamp=(\S+)/) {
	$cnt++;
	my $t = hex($1);
        if(defined $tlast) {
	    my $dt = $t - $tlast;
	    print "$dt\n";
	    if(!defined $tmin || $dt < $tmin) { $tmin = $dt; }
	    if(!defined $tmax || $dt > $tmax) { $tmax = $dt; }
	}
        $tlast = $t;
    }
}
my $tminusec = $tmin/40;
my $tmaxusec = $tmax/40;
warn "$cnt events.\n";
warn sprintf "Minimum delta time = %2.2f usec.\n", $tminusec;
warn sprintf "Maximum delta time = %2.2f usec.\n", $tmaxusec;

__END__

