#!/usr/bin/perl

# tagdomapp
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Mon Jun 14 15:08:27 2004

package TAGDOMAPP;
use strict;

print "Welcome to $0.\n";

my $tag;
do {
    print "(N)ew tag or (B)FD-based tag? "; 
    my $resp = <STDIN>; chomp $resp;
    if($resp =~ /^n/i) {
	print "Enter tag name: "; $tag = <STDIN>; chomp $tag;
    } elsif($resp =~ /b/i) {
	my $log = `cvs log project.mk | grep V`;
	my $def = "";
	print "List of existing tags:\n$log\n";
	if($log =~ /(V\d\d-\d\d-\d\d)/) { $def = $1; }
	print "Enter most recent BFD tag for this project [$def]: ";
	my $bfd = <STDIN>; chomp $bfd;
	if($bfd eq "") { $bfd = $def; }
	my $major;
	my $minor;
	my $bug;
	if($bfd =~ /V(\d\d)-(\d\d)-(\d\d)/) {
	    $major = $1;
	    $minor = $2;
	    $bug   = $3;
	    print "Are you creating a (major), (minor), or (bug) release? ";
	    my $resp = <STDIN>; chomp $resp;
	    if($resp =~ /^ma/) {
		$major++;
		$tag = "V$major"."-$minor"."-$bug";
	    } elsif($resp =~ /^mi/) {
		$minor++;
		$tag = "V$major"."-$minor"."-$bug";
	    } elsif($resp =~ /^b/) {
		$bug++;
		$tag = "V$major"."-$minor"."-$bug";
	    } else {
		print "Huh?\n";
	    }
	}
    } 
} until defined $tag;

print "Create new release with release tag \"$tag\"? ";
chomp(my $resp = <STDIN>);
exit if($resp !~ /^y/i);

my $header = "public/domapp_common/version.h";
die "Can't find current $header!  Old version of domapp?\n" unless -f $header;
print "Updating $header...\n";
print `cvs update $header`;

print "Creating new $header...\n";
open H, ">$header" || die "Can't open $header: $!\n";
print H "#define DOMAPP_RELEASE \"$tag\"\n";
close H;
print "New $header is:\n".`cat $header`;

print "Result of cvs diff --brief:\n".`cvs diff --brief`;

print "Commit current version of domapp to CVS? ";
chomp(my $resp = <STDIN>);
if($resp =~ /^y/) {
    print `cvs commit -m "Tagging current version as $tag..."`;
}

__END__

